# Permalinks
permalink:        pretty

# Settings
gems:             [jekyll-paginate]
markdown:         kramdown
destination:      ./_gh_pages
exclude:          ["README.md"]
paginate:         10
encoding:         UTF-8
future:           false
name:             Built With React
url:              http://builtwithreact.io
description:      "User interfaces built with React."
