version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/built-with-react
  test:
    build: .
    volumes:
      - .:/built-with-react
    command: bash script/cibuild